development:
  adapter: redis

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:58685969c0b3dbc548b0ff062586f17a@scat.redistogo.com:11754/
  channel_prefix: DiscordClone_production
